import type { Template } from "@/types";

export const TEMPLATES: Template[] = [
  // ── FREE TEMPLATES ──────────────────────────────────────────
  {
    id: "business-proposal",
    title: "Business Proposal",
    description: "A clean, professional proposal for business partnerships and services.",
    category: "Business",
    isPremium: false,
    color: "from-blue-500 to-indigo-600",
    icon: "💼",
    fields: [
      { key: "clientName", label: "Client Name", type: "text", placeholder: "Acme Corp" },
      { key: "yourName", label: "Your Name / Company", type: "text", placeholder: "Your Company LLC" },
      { key: "projectTitle", label: "Project Title", type: "text", placeholder: "Digital Transformation Initiative" },
      { key: "proposalDate", label: "Proposal Date", type: "date", placeholder: "" },
      { key: "validUntil", label: "Valid Until", type: "date", placeholder: "" },
      { key: "executiveSummary", label: "Executive Summary", type: "textarea", placeholder: "Brief overview of what you're proposing and why..." },
      { key: "scope", label: "Scope of Work", type: "textarea", placeholder: "Detailed description of services/deliverables..." },
      { key: "timeline", label: "Timeline", type: "textarea", placeholder: "Phase 1: Week 1-2 — Discovery\nPhase 2: Week 3-6 — Development..." },
      { key: "investment", label: "Investment / Pricing", type: "textarea", placeholder: "Total investment: $X,XXX\nPayment terms: 50% upfront, 50% on delivery" },
      { key: "yourEmail", label: "Your Email", type: "text", placeholder: "you@company.com" },
    ],
    defaultContent: {
      clientName: "Acme Corp",
      yourName: "Your Company LLC",
      projectTitle: "Digital Transformation Initiative",
      proposalDate: new Date().toISOString().split("T")[0],
      validUntil: new Date(Date.now() + 30 * 86400000).toISOString().split("T")[0],
      executiveSummary: "We are pleased to present this proposal for a comprehensive digital transformation initiative designed to modernize your operations and drive significant business growth.",
      scope: "• Discovery & Strategy (2 weeks)\n• System Architecture Design\n• Development & Implementation\n• Testing & Quality Assurance\n• Deployment & Training\n• 3 months post-launch support",
      timeline: "Phase 1 (Weeks 1-2): Discovery & Planning\nPhase 2 (Weeks 3-8): Development\nPhase 3 (Weeks 9-10): Testing & Launch",
      investment: "Total Investment: $15,000\n\nPayment Schedule:\n• 40% upon signing ($6,000)\n• 40% at milestone 2 ($6,000)\n• 20% on final delivery ($3,000)",
      yourEmail: "contact@yourcompany.com",
    },
  },
  {
    id: "project-proposal",
    title: "Project Proposal",
    description: "Perfect for pitching a new project to stakeholders or clients.",
    category: "Project",
    isPremium: false,
    color: "from-emerald-500 to-teal-600",
    icon: "📋",
    fields: [
      { key: "projectName", label: "Project Name", type: "text", placeholder: "New Mobile App" },
      { key: "preparedBy", label: "Prepared By", type: "text", placeholder: "Your Name" },
      { key: "preparedFor", label: "Prepared For", type: "text", placeholder: "Client / Stakeholder" },
      { key: "date", label: "Date", type: "date", placeholder: "" },
      { key: "objective", label: "Project Objective", type: "textarea", placeholder: "What problem does this project solve?" },
      { key: "deliverables", label: "Key Deliverables", type: "textarea", placeholder: "1. Feature A\n2. Feature B\n3. Feature C" },
      { key: "budget", label: "Estimated Budget", type: "text", placeholder: "$10,000" },
      { key: "duration", label: "Project Duration", type: "text", placeholder: "3 months" },
      { key: "risks", label: "Risks & Mitigation", type: "textarea", placeholder: "Risk 1: ... Mitigation: ..." },
    ],
    defaultContent: {
      projectName: "New Mobile App",
      preparedBy: "Your Name",
      preparedFor: "Stakeholders",
      date: new Date().toISOString().split("T")[0],
      objective: "This project aims to develop a mobile application that simplifies customer onboarding, reducing the time-to-value by 60% and improving customer satisfaction scores.",
      deliverables: "1. iOS and Android mobile applications\n2. Admin dashboard\n3. API integration with existing systems\n4. User documentation and training materials",
      budget: "$25,000",
      duration: "4 months",
      risks: "Risk: Scope creep — Mitigation: Weekly check-ins and change request process\nRisk: Integration delays — Mitigation: Early API access and sandbox environment",
    },
  },
  {
    id: "freelance-quote",
    title: "Freelance Quote",
    description: "Send a clean, detailed quote to your freelance clients.",
    category: "Freelance",
    isPremium: false,
    color: "from-orange-500 to-amber-600",
    icon: "🧾",
    fields: [
      { key: "freelancerName", label: "Your Name", type: "text", placeholder: "Jane Smith" },
      { key: "clientName", label: "Client Name", type: "text", placeholder: "John Doe" },
      { key: "projectDesc", label: "Project Description", type: "text", placeholder: "Website redesign" },
      { key: "quoteDate", label: "Quote Date", type: "date", placeholder: "" },
      { key: "validFor", label: "Valid For", type: "text", placeholder: "14 days" },
      { key: "services", label: "Services & Rates", type: "textarea", placeholder: "Design: $80/hr × 10hrs = $800\nDevelopment: $100/hr × 20hrs = $2,000" },
      { key: "total", label: "Total Amount", type: "text", placeholder: "$2,800" },
      { key: "paymentTerms", label: "Payment Terms", type: "textarea", placeholder: "50% upfront, 50% on completion. Net 14." },
      { key: "contact", label: "Your Contact", type: "text", placeholder: "jane@freelance.com" },
    ],
    defaultContent: {
      freelancerName: "Jane Smith",
      clientName: "Client Name",
      projectDesc: "Website Redesign",
      quoteDate: new Date().toISOString().split("T")[0],
      validFor: "14 days",
      services: "UI/UX Design: $80/hr × 8hrs = $640\nFront-end Development: $100/hr × 16hrs = $1,600\nContent Migration: $50/hr × 4hrs = $200\n\nSubtotal: $2,440",
      total: "$2,440",
      paymentTerms: "• 50% deposit required to begin work ($1,220)\n• Remaining 50% due upon project completion\n• Net 14 payment terms\n• Late payments subject to 1.5% monthly fee",
      contact: "jane@freelance.com | +1 (555) 000-0000",
    },
  },

  // ── PREMIUM TEMPLATES ────────────────────────────────────────
  {
    id: "sales-proposal",
    title: "Sales Proposal",
    description: "High-converting sales proposal to close more deals.",
    category: "Sales",
    isPremium: true,
    color: "from-purple-500 to-violet-600",
    icon: "🚀",
    fields: [
      { key: "clientName", label: "Prospect Name", type: "text", placeholder: "Big Company Inc" },
      { key: "salesperson", label: "Account Executive", type: "text", placeholder: "Your Name" },
      { key: "date", label: "Date", type: "date", placeholder: "" },
      { key: "painPoints", label: "Their Pain Points", type: "textarea", placeholder: "What challenges are they facing?" },
      { key: "solution", label: "Your Solution", type: "textarea", placeholder: "How your product/service solves it..." },
      { key: "benefits", label: "Key Benefits", type: "textarea", placeholder: "• Benefit 1\n• Benefit 2\n• Benefit 3" },
      { key: "pricing", label: "Pricing", type: "textarea", placeholder: "Starter: $X/mo\nPro: $Y/mo" },
      { key: "cta", label: "Call to Action", type: "text", placeholder: "Schedule a 30-min call" },
    ],
    defaultContent: {
      clientName: "Prospect Company",
      salesperson: "Your Name",
      date: new Date().toISOString().split("T")[0],
      painPoints: "Based on our discovery call, we understand you're facing:\n• Manual processes consuming 20+ hours/week\n• Lack of real-time visibility into operations\n• Customer satisfaction declining due to slow response times",
      solution: "Our platform automates your core workflows, provides real-time dashboards, and integrates with your existing tools — all without requiring any code changes.",
      benefits: "✓ Save 20+ hours/week on manual tasks\n✓ 3x faster customer response time\n✓ Full ROI typically achieved in 90 days\n✓ Dedicated onboarding and support",
      pricing: "Professional Plan: $299/month\n• Up to 10 users\n• All core features\n• Priority support\n• Custom integrations\n\nEnterprise: Custom pricing",
      cta: "Schedule your free 30-minute demo at calendly.com/yourname",
    },
  },
  {
    id: "marketing-proposal",
    title: "Marketing Proposal",
    description: "Present a complete marketing strategy to win new clients.",
    category: "Marketing",
    isPremium: true,
    color: "from-pink-500 to-rose-600",
    icon: "📣",
    fields: [
      { key: "clientName", label: "Client Name", type: "text", placeholder: "Brand Co." },
      { key: "agency", label: "Agency Name", type: "text", placeholder: "Your Agency" },
      { key: "date", label: "Proposal Date", type: "date", placeholder: "" },
      { key: "goals", label: "Marketing Goals", type: "textarea", placeholder: "Increase brand awareness, generate 500 leads/mo..." },
      { key: "strategy", label: "Strategy Overview", type: "textarea", placeholder: "Content marketing + paid ads + SEO..." },
      { key: "channels", label: "Channels & Tactics", type: "textarea", placeholder: "Social Media, Google Ads, Email, SEO..." },
      { key: "kpis", label: "KPIs & Metrics", type: "textarea", placeholder: "MQL target, CPA, ROAS..." },
      { key: "budget", label: "Monthly Budget", type: "text", placeholder: "$5,000/month" },
      { key: "retainer", label: "Agency Retainer", type: "text", placeholder: "$3,000/month" },
    ],
    defaultContent: {
      clientName: "Brand Co.",
      agency: "Your Agency",
      date: new Date().toISOString().split("T")[0],
      goals: "• Increase organic traffic by 150% in 6 months\n• Generate 300+ qualified leads per month\n• Achieve 3x ROAS on paid campaigns\n• Grow social following by 10,000",
      strategy: "A multi-channel approach combining organic content, targeted paid media, and email nurture sequences to drive awareness, consideration, and conversion across the funnel.",
      channels: "1. SEO & Content Marketing — 2 blogs/week, pillar pages\n2. Google Ads — Search + Display campaigns\n3. LinkedIn Ads — B2B lead generation\n4. Email Marketing — Weekly newsletter + drip sequences\n5. Social Media — Daily posts across Instagram & LinkedIn",
      kpis: "• Monthly Qualified Leads: 300+\n• Cost Per Lead: <$25\n• Email Open Rate: >30%\n• Organic Traffic Growth: +20% MoM",
      budget: "$8,000/month (ad spend)",
      retainer: "$4,000/month (agency fee)",
    },
  },
  {
    id: "partnership-agreement",
    title: "Partnership Agreement",
    description: "Formal partnership proposal outlining terms and mutual benefits.",
    category: "Business",
    isPremium: true,
    color: "from-cyan-500 to-blue-600",
    icon: "🤝",
    fields: [
      { key: "party1", label: "Party 1 (You)", type: "text", placeholder: "Your Company" },
      { key: "party2", label: "Party 2 (Partner)", type: "text", placeholder: "Partner Company" },
      { key: "date", label: "Effective Date", type: "date", placeholder: "" },
      { key: "purpose", label: "Partnership Purpose", type: "textarea", placeholder: "What is the goal of this partnership?" },
      { key: "responsibilities1", label: "Your Responsibilities", type: "textarea", placeholder: "What you will contribute..." },
      { key: "responsibilities2", label: "Partner Responsibilities", type: "textarea", placeholder: "What they will contribute..." },
      { key: "revenueSplit", label: "Revenue Split", type: "text", placeholder: "50/50 or 60/40" },
      { key: "duration", label: "Partnership Duration", type: "text", placeholder: "12 months, renewable" },
      { key: "termination", label: "Termination Clause", type: "textarea", placeholder: "Either party may terminate with 30 days written notice..." },
    ],
    defaultContent: {
      party1: "Your Company LLC",
      party2: "Partner Company Inc",
      date: new Date().toISOString().split("T")[0],
      purpose: "This partnership aims to combine the complementary strengths of both parties to deliver enhanced solutions to shared target markets, increasing revenue and market reach for both organizations.",
      responsibilities1: "• Provide platform technology and development resources\n• Handle billing and customer support\n• Lead marketing and demand generation\n• Manage customer success",
      responsibilities2: "• Provide industry expertise and domain knowledge\n• Contribute existing client relationships\n• Deliver specialized services\n• Participate in joint marketing activities",
      revenueSplit: "60% Party 1 / 40% Party 2 on jointly generated revenue",
      duration: "Initial term: 12 months, auto-renewing annually",
      termination: "Either party may terminate this agreement with 60 days written notice. Upon termination, existing customer contracts will be honored through their natural end dates.",
    },
  },
  {
    id: "software-sow",
    title: "Software Development SOW",
    description: "Statement of Work for software and web development projects.",
    category: "Technology",
    isPremium: true,
    color: "from-slate-600 to-gray-800",
    icon: "💻",
    fields: [
      { key: "client", label: "Client", type: "text", placeholder: "Client Company" },
      { key: "vendor", label: "Vendor / Dev Agency", type: "text", placeholder: "Dev Agency LLC" },
      { key: "projectName", label: "Project Name", type: "text", placeholder: "Customer Portal v2" },
      { key: "startDate", label: "Start Date", type: "date", placeholder: "" },
      { key: "endDate", label: "End Date", type: "date", placeholder: "" },
      { key: "techStack", label: "Technology Stack", type: "textarea", placeholder: "React, Node.js, PostgreSQL..." },
      { key: "features", label: "Features & Modules", type: "textarea", placeholder: "1. User Authentication\n2. Dashboard\n..." },
      { key: "acceptance", label: "Acceptance Criteria", type: "textarea", placeholder: "Each feature must pass QA testing and client UAT..." },
      { key: "rate", label: "Billing Rate", type: "text", placeholder: "$150/hr or $25,000 fixed" },
      { key: "changePolicy", label: "Change Request Policy", type: "textarea", placeholder: "Changes outside original scope billed at $X/hr..." },
    ],
    defaultContent: {
      client: "Client Company",
      vendor: "Dev Agency LLC",
      projectName: "Customer Portal v2",
      startDate: new Date().toISOString().split("T")[0],
      endDate: new Date(Date.now() + 90 * 86400000).toISOString().split("T")[0],
      techStack: "Frontend: Next.js, TypeScript, Tailwind CSS\nBackend: Node.js, Express\nDatabase: PostgreSQL (Supabase)\nHosting: Vercel + Supabase",
      features: "Module 1: Authentication (login, signup, SSO)\nModule 2: User Dashboard with analytics\nModule 3: Data management CRUD\nModule 4: Notification system (email + in-app)\nModule 5: Admin panel\nModule 6: API documentation",
      acceptance: "• All features pass unit and integration tests\n• Performance: page load <2s on 4G\n• Cross-browser compatibility (Chrome, Firefox, Safari)\n• Client UAT sign-off within 5 business days\n• Zero critical security vulnerabilities",
      rate: "Fixed price: $28,000\nMilestone 1 (Design): $7,000\nMilestone 2 (Core dev): $14,000\nMilestone 3 (Launch): $7,000",
      changePolicy: "Changes outside agreed scope submitted via written request. Estimated at $140/hr. Client approval required before work begins.",
    },
  },
  {
    id: "agency-retainer",
    title: "Agency Retainer",
    description: "Monthly retainer agreement for ongoing agency services.",
    category: "Agency",
    isPremium: true,
    color: "from-yellow-500 to-orange-600",
    icon: "📅",
    fields: [
      { key: "agencyName", label: "Agency Name", type: "text", placeholder: "Creative Agency Co." },
      { key: "clientName", label: "Client Name", type: "text", placeholder: "Client Brand" },
      { key: "retainerFee", label: "Monthly Retainer Fee", type: "text", placeholder: "$5,000/month" },
      { key: "hoursIncluded", label: "Hours Included", type: "text", placeholder: "40 hours/month" },
      { key: "services", label: "Services Included", type: "textarea", placeholder: "Social media management, content creation..." },
      { key: "startDate", label: "Start Date", type: "date", placeholder: "" },
      { key: "deliverables", label: "Monthly Deliverables", type: "textarea", placeholder: "8 social posts, 2 blog posts, monthly report..." },
      { key: "reporting", label: "Reporting", type: "textarea", placeholder: "Monthly performance report delivered by 5th..." },
      { key: "overageRate", label: "Overage Rate", type: "text", placeholder: "$150/hr beyond included hours" },
    ],
    defaultContent: {
      agencyName: "Creative Agency Co.",
      clientName: "Client Brand",
      retainerFee: "$5,000/month",
      hoursIncluded: "40 hours/month",
      services: "• Social media management (Instagram, LinkedIn, Twitter)\n• Content creation (graphics + copywriting)\n• Monthly email newsletter\n• Paid ad management (up to $10K spend)\n• Monthly strategy call",
      startDate: new Date().toISOString().split("T")[0],
      deliverables: "• 20 social media posts (graphics + copy)\n• 2 long-form blog articles\n• 1 monthly email newsletter\n• Weekly ad performance optimization\n• Monthly analytics report",
      reporting: "Monthly performance report delivered by the 5th of each month, covering reach, engagement, leads generated, and ad performance vs. benchmarks.",
      overageRate: "$150/hr for hours exceeding monthly retainer. Pre-approved by client before billing.",
    },
  },
  {
    id: "event-proposal",
    title: "Event Proposal",
    description: "Professional proposal for corporate events, conferences, or activations.",
    category: "Events",
    isPremium: true,
    color: "from-fuchsia-500 to-purple-600",
    icon: "🎪",
    fields: [
      { key: "eventName", label: "Event Name", type: "text", placeholder: "Annual Sales Conference 2025" },
      { key: "client", label: "Client / Organizer", type: "text", placeholder: "Company Name" },
      { key: "planner", label: "Event Planner / Company", type: "text", placeholder: "Events by You" },
      { key: "eventDate", label: "Event Date", type: "date", placeholder: "" },
      { key: "venue", label: "Proposed Venue", type: "text", placeholder: "The Grand Hotel, New York" },
      { key: "attendees", label: "Expected Attendees", type: "text", placeholder: "250 guests" },
      { key: "concept", label: "Event Concept", type: "textarea", placeholder: "Theme, atmosphere, experience..." },
      { key: "services", label: "Services Provided", type: "textarea", placeholder: "Venue sourcing, catering, AV, decor..." },
      { key: "budget", label: "Estimated Budget", type: "text", placeholder: "$50,000" },
    ],
    defaultContent: {
      eventName: "Annual Leadership Summit 2025",
      client: "Company Name",
      planner: "Events by You",
      eventDate: new Date(Date.now() + 60 * 86400000).toISOString().split("T")[0],
      venue: "The Grand Ballroom, Marriott Downtown",
      attendees: "150 executives",
      concept: "An intimate leadership summit focused on innovation and strategy. Clean, modern aesthetic with interactive workshops, keynote speakers, and networking dinners. Hybrid format with live streaming for remote attendees.",
      services: "• Venue sourcing and management\n• Catering (breakfast, lunch, dinner, cocktail hour)\n• AV and production (stage, lighting, sound)\n• Event design and décor\n• Speaker coordination\n• Registration and attendee management\n• Photography and videography\n• Post-event recap report",
      budget: "$45,000 (all-inclusive)",
    },
  },
  {
    id: "consulting-proposal",
    title: "Consulting Proposal",
    description: "Win consulting engagements with a structured, compelling proposal.",
    category: "Consulting",
    isPremium: true,
    color: "from-teal-500 to-emerald-600",
    icon: "🎯",
    fields: [
      { key: "consultantName", label: "Consultant / Firm", type: "text", placeholder: "Strategy Consulting Group" },
      { key: "clientName", label: "Client Name", type: "text", placeholder: "Target Corp" },
      { key: "engagement", label: "Engagement Title", type: "text", placeholder: "Operational Efficiency Review" },
      { key: "date", label: "Proposal Date", type: "date", placeholder: "" },
      { key: "problem", label: "Problem Statement", type: "textarea", placeholder: "The challenge the client is facing..." },
      { key: "approach", label: "Consulting Approach", type: "textarea", placeholder: "Phase 1: Assessment\nPhase 2: Analysis\nPhase 3: Recommendations" },
      { key: "expertise", label: "Why Us", type: "textarea", placeholder: "Relevant experience, case studies..." },
      { key: "fees", label: "Fees & Structure", type: "textarea", placeholder: "Daily rate: $X,XXX\nEngagement total: $XX,XXX" },
      { key: "nextSteps", label: "Next Steps", type: "textarea", placeholder: "1. Sign agreement\n2. Kick-off meeting\n..." },
    ],
    defaultContent: {
      consultantName: "Strategy Consulting Group",
      clientName: "Client Corp",
      engagement: "Operational Excellence Assessment",
      date: new Date().toISOString().split("T")[0],
      problem: "Client Corp is experiencing significant operational inefficiencies resulting in a 23% cost overrun and declining customer satisfaction. Manual processes, siloed data, and lack of standardization are the primary drivers.",
      approach: "Phase 1 — Current State Assessment (2 weeks)\nInterviews, process mapping, data analysis\n\nPhase 2 — Gap Analysis & Benchmarking (1 week)\nBenchmark against industry best practices\n\nPhase 3 — Recommendations & Roadmap (1 week)\nPrioritized initiative roadmap with ROI projections",
      expertise: "We have completed 40+ operational transformation engagements across manufacturing, logistics, and retail sectors. Average client outcome: 18% cost reduction within 12 months.",
      fees: "Engagement Fee: $28,000 (fixed)\n\nIncludes:\n• 4-week on-site engagement\n• Final recommendations deck\n• 90-day implementation roadmap\n• 2 follow-up calls post-delivery\n\nExpenses billed at cost with prior approval.",
      nextSteps: "1. Review and sign this proposal\n2. Schedule kick-off meeting\n3. Provide access to key stakeholders and data\n4. Begin Phase 1 assessment",
    },
  },
];

export function getTemplateById(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

export const FREE_TEMPLATES = TEMPLATES.filter((t) => !t.isPremium);
export const PREMIUM_TEMPLATES = TEMPLATES.filter((t) => t.isPremium);
